name: Acceptance Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect package manager
        id: detect-pm
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
            echo "cache=pnpm" >> $GITHUB_OUTPUT
            echo "install_cmd=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT
          elif [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "cache=yarn" >> $GITHUB_OUTPUT
            echo "install_cmd=yarn install --frozen-lockfile" >> $GITHUB_OUTPUT
          else
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "cache=npm" >> $GITHUB_OUTPUT
            echo "install_cmd=npm ci" >> $GITHUB_OUTPUT
          fi

      - name: Setup PNPM (if needed)
        if: steps.detect-pm.outputs.manager == 'pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            ~/.yarn/cache
            node_modules
          key: ${{ runner.os }}-${{ steps.detect-pm.outputs.cache }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}

      - name: Install dependencies
        run: ${{ steps.detect-pm.outputs.install_cmd }}

      - name: Ensure tsx available (optional)
        run: npx --yes tsx@4.7.0 --version

      - name: Show repository tree (debug)
        run: |
          ls -la
          echo "--- server dir ---"
          ls -la server || true

      - name: Start server robustly (with PID + readiness check)
        env:
          PORT: 5000
          JWT_SECRET: test_secret_for_ci_only_do_not_use_in_production
          JWT_ISSUER: nexo
          NODE_ENV: production
        shell: bash
        run: |
          set -e
          export PORT=5000
          # Build nếu có thể (không fail job nếu build lỗi)
          (pnpm -v && pnpm build) || true

          echo "Starting server…"
          (node dist/index.js || npx tsx server/index.ts) > server.log 2>&1 &
          SERVER_PID=$!
          echo "PID=$SERVER_PID"

          # Chờ health lên tối đa 20s; nếu process chết sớm hoặc health không lên thì in log và fail
          READY=0
          for i in {1..40}; do
            if curl -sf http://localhost:5000/api/health >/dev/null; then READY=1; break; fi
            if ! kill -0 "$SERVER_PID" 2>/dev/null; then
              echo "Server process exited prematurely. Last logs:"; tail -n 200 server.log; exit 1
            fi
            sleep 0.5
          done
          if [ "$READY" -ne 1 ]; then
            echo "Health never became ready. Last logs:"; tail -n 200 server.log; exit 1
          fi
          echo "Server is up."

      - name: Test health endpoint performance
        shell: bash
        run: |
          # warm-up
          for i in {1..3}; do curl -s http://localhost:5000/api/health >/dev/null; done
          FAIL=0
          for i in {1..5}; do
            T=$(curl -s -w "%{time_total}" -o /dev/null http://localhost:5000/api/health)
            ms=$(python -c "print(int(float('$T')*1000))")
            echo "health_ms=$ms"
            [ "$ms" -lt 200 ] || FAIL=1
          done
          exit $FAIL

      - name: Force SQLite write & assert DB file
        shell: bash
        run: |
          # kích ghi DB (endpoint có thể không tồn tại — không fail ở POST)
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:5000/api/messages \
            -H "Content-Type: application/json" \
            -d '{"conversation_id":"ci-acc","cipher":"X1","nonce":"N1","ad":{"type":"text"}}' || true)
          echo "messages_post_status=$STATUS"
          sleep 0.5
          ls -lh ./data || true
          test -f ./data/nexo.db

      - name: Print last server logs
        if: always()
        run: |
          echo "---- server.log (last 200 lines) ----"
          tail -n 200 server.log || true
